# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ThriveTalk

on:
  push:
    branches: ["main", "master"]
  pull_request:
  workflow_call:
    secrets:
      # SonarQube token
      SONAR_TOKEN:
        required: true

env:
  PYTHON_VERSION: '3.10'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
          unzip sonar-scanner-cli-4.7.0.2747-linux.zip
          export PATH=$PATH:$(pwd)/sonar-scanner-4.7.0.2747-linux/bin

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint action
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unittests
        run: pytest

      - name: Run SonarQube analysis
        run: |
          sonar-scanner \
            -Dsonar.projectKey=thrivetalk \
            -Dsonar.sources=. \
            -Dsonar.projectBaseDir=. \
            -Dsonar.tests=tests \
            -Dsonar.python.coverage.reportPaths=coverage.xml \
            -Dsonar.python.xunit.reportPaths=test-results.xml \
            -Dsonar.verbose=true
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/17*/x64
          pythonLocation: /opt/hostedtoolcache/Python/3.10.14/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.14/x64/lib
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
